# .air.toml

# The working directory
root = "."
tmp_dir = "tmp"
build = "main.go"
bin = "bin/app"

# Watch these files and directories
[watch]
  # Watch current directory
  ".": {
    # Extensions to watch
    exts = ["go", "tpl", "tmpl", "html"]
    # Ignore these directories
    ignore = ["tmp", "bin"]
  }

# Logging
[log]
  level = "debug"

# Commands to run before/after building
[cmd]
  before_build = ""
  after_build = ""
